#!/bin/sh

set -e

build="tmp"
src="./taglib"
sdk="/opt/wasi-sdk"

cmake \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
    -DWITH_ZLIB=OFF \
    -DBUILD_SHARED_LIBS=OFF \
    -DVISIBILITY_HIDDEN=ON \
    -DBUILD_TESTING=OFF \
    -DWASI_SDK_PREFIX="$sdk" \
    -DCMAKE_TOOLCHAIN_FILE="$sdk"/share/cmake/wasi-sdk.cmake \
    -B "$build" \
    "$src"

cmake \
    --build "$build/bindings/wasm/" \
    --target taglib_wasm

mv "$build/bindings/wasm/taglib_wasm.wasm" taglib.wasm

wasm-opt --strip -c -O3 taglib.wasm -o taglib.wasm
