name: Reproducible build
on:
  workflow_dispatch:
  push:
    tags:
      - "*"
jobs:
  build:
    name: Build and attest
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      attestations: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Compute original checksum
        run: sha256sum taglib.wasm > taglib.wasm.sum
      - name: Build taglib.wasm
        run: |
          rm taglib.wasm
          ./build/build-docker.sh
      - name: Verify checksum unchanged
        run: |
          sha256sum -c taglib.wasm.sum || exit 1
      - name: Attest build provenance
        uses: actions/attest-build-provenance@v3
        with:
          subject-path: |
            taglib.wasm
